### ISSUE TITLE
Which tool do you use for optical flow visualization as in Figure. 3 ?

### ISSUE THREAD

**Issue by jinx2018** [denfed/heartheflow#3]
Hi! Your work is great. And could you please tell which tool do you use for the visualization of the extracted flow show. in Figure. 3 in you paper?  

I use the  `flow_vis` package for visualization but the visualization is not so clear to show the shape of the target object

**Comment by denfed** [comment]
Hello! Thank you for your interest in our work!

If i recall correctly, we used: https://github.com/tomrunia/OpticalFlow_Visualization

I will take a look at some of the older code for this project soon and double check, but I believe we used that repo.
